### ISSUE TITLE
Replace TODO on markdowns with necessary information

### ISSUE THREAD

**Issue by medegw01** [medegw01/RaccoonChessSigma#2]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines TODO-LINK-TO-CONTRIBUTER-GUILD
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I will like to see:
- useful information on all markdowns instead of TODO
- a logo for RaccoonChessSignma(rcSigma)

#### Is your feature request related to a problem? Please describe it

I wanted to see documentations, but I saw TODO across all the markdown files. I want to see more details

#### Additional context

See https://github.com/medegw01/raccoon.js for example of documentations

#### How will you/everyone benefit from this feature?

This feature will give better understanding of code use
